# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-29 03:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_pub_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='pub_date',
            new_name='pub_time',
        ),
    ]
